[[protocols]]
name = "HUAYU"
protocol = "sony"
#variant = "rc6_mce"
[protocols.scancodes]
0x10009    = "KEY_NUMERIC_0"
0x10000    = "KEY_NUMERIC_1"
0x10001    = "KEY_NUMERIC_2"
0x10002    = "KEY_NUMERIC_3"
0x10003    = "KEY_NUMERIC_4"
0x10004    = "KEY_NUMERIC_5"
0x10005    = "KEY_NUMERIC_6"
0x10006    = "KEY_NUMERIC_7"
0x10007    = "KEY_NUMERIC_8"
0x10008    = "KEY_NUMERIC_9"
0x800f040a = "KEY_DELETE"
0x10065    = "KEY_ENTER"
0x10015    = "KEY_POWER"
0x111xxxxx = "KEY_MEDIA"
0x10014    = "KEY_MUTE"
0x800f040f = "KEY_INFO"
0x10012    = "KEY_VOLUMEUP"
0x10013    = "KEY_VOLUMEDOWN"
0x10010    = "KEY_CHANNELUP"
0x10011    = "KEY_CHANNELDOWN"
0x97001c   = "KEY_FASTFORWARD"
0x97001b   = "KEY_REWIND"
0x97001a   = "KEY_PLAY"
0x970020   = "KEY_RECORD"
0x970019   = "KEY_PAUSE"
0x970018   = "KEY_STOP"
0x97003d   = "KEY_NEXT"
0x97003c   = "KEY_PREVIOUS"
0x800f041c = "KEY_NUMERIC_POUND"
0x800f041d = "KEY_NUMERIC_STAR"
0x10074    = "KEY_UP"
0x10075    = "KEY_DOWN"
0x10034    = "KEY_LEFT"
0x10033    = "KEY_RIGHT"
0x10060    = "KEY_ESC"
0x10063    = "KEY_EXIT"
0x970023   = "KEY_BACK"
#0x800f0424 = "KEY_DVD"
0x800f0425 = "KEY_TUNER"
0x800f0426 = "KEY_EPG"
0x800f0427 = "KEY_ZOOM"
0x800f0432 = "KEY_MODE"
0x800f33   = "KEY_PRESENTATION"
0x800f0434 = "KEY_EJECTCD"
0x800f043a = "KEY_BRIGHTNESSUP"
0x1a0057 = "KEY_TV"
0x10017    = "KEY_AUDIO"
0x800f0448 = "KEY_PVR"
0x800f0449 = "KEY_CAMERA"
0x800f044a = "KEY_VIDEO"
0x800f044c = "KEY_LANGUAGE"
0x800f044d = "KEY_TITLE"
0x800f044e = "KEY_PRINT"
0x800f0450 = "KEY_RADIO"
0x800f045a = "KEY_SUBTITLE"
0x970025   = "KEY_RED"
0x800f045c = "KEY_GREEN"
0x800f045d = "KEY_YELLOW"
0x970024   = "KEY_BLUE"
#0xc40047   = "KEY_POWER2"
0xc40046   = "KEY_MESSENGER"
0xc40047 = "KEY_PLAYPAUSE"
0x1a007c   = "KEY_DVD"
0x1a007e   = "KEY_END"
0x800f0480 = "KEY_BRIGHTNESSDOWN"
0x800f0481 = "KEY_PLAYPAUSE"
0xc4004d   = "KEY_HELP"
0x10025    = "KEY_TAB"
0x77000d   = "KEY_SPACE"
