[[protocols]]
name = "ToshibaTV"
protocol = "nec"
variant = "nec32"

[protocols.scancodes]
0x4014 = "KEY_POWER"
0x401a = "KEY_VOLUMEUP"
0x401e = "KEY_VOLUMEDOWN"
0x4040 = "KEY_BACK"
0x400a = "KEY_ENTER"
0x43 = "KEY_FORWARD"
0x401d = "KEY_DOWN"
0x4046 = "KEY_LEFT"
0x4047 = "KEY_RIGHT"
0x4019 = "KEY_UP"
0x4010 = "KEY_MUTE"
